services:
  - type: web
    name: flask-mongo-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://nathbiswa920:<admin@1234>@cluster0.ijejoqb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: SECRET_KEY
        value: supersecretkey

  # - type: web
  #   name: flask-mongo-app
  #   env: python
  #   buildCommand: pip install -r requirements.txt
  #   startCommand: gunicorn app:app
  #   plan: free
  #   envVars:
  #     - key: MONGO_URI
  #       value: mongodb+srv://<username>:<password>@cluster0.mongodb.net/<dbname>?retryWrites=true&w=majority    
  #     - key: SECRET_KEY
  #       value: your_flask_secret_key  